### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [itzmeanjan/trackm3#1]
Hi @itzmeanjan  Tobaloidee again..Here's what I have for this project..Combination of Electron, Location Tracker and LIVE dot.

![PRES-01](https://user-images.githubusercontent.com/36028424/57270370-8ee4cd00-70bd-11e9-8353-17dbbd3c66e3.png)

**Comment by itzmeanjan** [comment]
Looks great @Tobaloidee :clap: 

Please submit a PR .

**Comment by Tobaloidee** [comment]
Hello @itzmeanjan  here is the PR #2 for this project's logo.. 

All other versions and file formats you can download [HERE](https://drive.google.com/drive/u/1/folders/1A8tRGMiTpnsNRo2Theqb9kUqCGWn1oh5)

**Comment by itzmeanjan** [comment]
Merging done @Tobaloidee :relaxed: 

Btw Great work :+1:
